[build]
  command = "pnpm --filter frontend build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_API_URL = ""
  NEXT_PUBLIC_ADMIN_URL = ""
  REVALIDATE_SECRET = ""