// Copies the live collections into frontend/lib/cms/fixtures, which the
// site uses as its fallback and `npm run seed` writes into an empty database. Run it after changing
// content in the admin so the fallbacks stay current:  npm run content:snapshot
import "dotenv/config";
import { execFileSync } from "child_process";
import { writeFileSync } from "fs";
import path from "path";
import prisma from "../src/config/prisma";

const FRONTEND = path.resolve(__dirname, "../../frontend");
const OUT = path.join(FRONTEND, "lib/cms/fixtures");
// Figma asset links from design handoff expire after a few days, so they're never worth keeping.
const EXPIRING = /^https:\/\/www\.figma\.com\/api\/mcp\/asset\//;

const warnings: string[] = [];
const media = (value: string | null, where: string) => {
  if (value && EXPIRING.test(value)) {
    warnings.push(`${where}: dropped an expired Figma link`);
    return null;
  }
  return value;
};

function write(file: string, header: string, exports: [string, string, unknown][]) {
  const types = [...new Set(exports.map(([, type]) => type))].join(", ");
  const body = exports.map(([name, type, value]) => `export const ${name}: ${type}[] = ${JSON.stringify(value, null, 2)};\n`).join("\n");
  const source = `// GENERATED by \`npm run content:snapshot\` in backend/ from the live database. ${header}\nimport type { ${types} } from "./types";\n\n${body}`;
  writeFileSync(path.join(OUT, file), source);
  console.log(`wrote lib/cms/fixtures/${file}`);
}

async function main() {
  // Same order as the public API, so the fallback lists items exactly like the live site.
  const order = [{ order: "asc" as const }, { createdAt: "desc" as const }];
  const [integrations, features, useCases, testimonials, scaling, roi, blogs] = await Promise.all([
    prisma.integration.findMany({ orderBy: [{ order: "asc" }, { name: "asc" }] }),
    prisma.feature.findMany({ orderBy: order }),
    prisma.useCase.findMany({ orderBy: order }),
    prisma.testimonial.findMany({ orderBy: order }),
    prisma.scalingStep.findMany({ orderBy: [{ isCard: "asc" }, ...order] }),
    prisma.industryROI.findMany({ orderBy: order }),
    prisma.blog.findMany({ orderBy: [{ publishedAt: "desc" }, { createdAt: "desc" }] }),
  ]);

  write("collections.ts", "Edit content in the admin, then re-run.", [
    ["INTEGRATIONS", "IntegrationFixture", integrations.map(({ id, name, logo, description, category, isActive, order }) => ({ id, name, logo: media(logo, `integration ${name}`), description, category, isActive, order }))],
    ["FEATURES", "FeatureFixture", features.map(({ id, title, description, videoUrl, thumbnail, apps, group, isActive, order }) => ({ id, title, description, videoUrl: media(videoUrl, `feature ${title}`), thumbnail: media(thumbnail, `feature ${title}`), apps, group, isActive, order }))],
    ["USE_CASES", "UseCaseFixture", useCases.map(({ id, title, description, icon, category, isActive, order }) => ({ id, title, description, icon: media(icon, `use case ${title}`), category, isActive, order }))],
    ["TESTIMONIALS", "TestimonialFixture", testimonials.map(({ id, quote, name, role, company, avatar, rating, isActive, order }) => ({ id, quote, name, role, company, avatar: media(avatar, `testimonial ${name}`), rating, isActive, order }))],
    ["SCALING_STEPS", "ScalingStepFixture", scaling.map(({ id, step, title, body, icon, isCard, order }) => ({ id, step, title, body, icon: media(icon, `scaling step ${title}`), isCard, order }))],
    ["INDUSTRY_ROI", "IndustryRoiFixture", roi.map(({ id, industry, cvr, showUp, image, useCases, isActive, order }) => ({ id, industry, cvr, showUp, image: media(image, `industry ROI ${industry}`), useCases, isActive, order }))],
  ]);

  write("blog-posts.ts", "Server-only: includes full post bodies.", [
    [
      "BLOG_POSTS",
      "BlogPostFixture",
      blogs.map((b) => {
        // A published post needs a publish date, or the site can't open it.
        const publishedAt = b.publishedAt ?? (b.status === "published" ? b.createdAt : null);
        if (!b.publishedAt && publishedAt) warnings.push(`blog "${b.slug}": published without a date; used its creation date`);
        return {
          id: b.id,
          title: b.title,
          slug: b.slug,
          excerpt: b.excerpt,
          content: b.content,
          image: media(b.image, `blog ${b.slug}`),
          author: b.author,
          category: b.category,
          readTime: b.readTime,
          tags: b.tags,
          status: b.status,
          publishedAt: publishedAt?.toISOString() ?? null,
          metaTitle: b.metaTitle,
          metaDescription: b.metaDescription,
          createdAt: b.createdAt.toISOString(),
        };
      }),
    ],
  ]);


  for (const w of warnings) console.warn(`note: ${w}`);
  execFileSync(process.execPath, [path.join(FRONTEND, "scripts/sync-cms-schema.mjs")], { stdio: "inherit" });
}

main()
  .catch((err) => {
    console.error("Snapshot failed:", err.message ?? err);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
