// GENERATED by `npm run content:snapshot` in backend/ from the live database. Server-only: includes full post bodies.
import type { BlogPostFixture } from "./types";

export const BLOG_POSTS: BlogPostFixture[] = [
  {
    "id": "cmu4vnfzi0019rv3j0mw0nreg",
    "title": "Why AI Agents Are the Future of Work",
    "slug": "why-ai-agents-are-the-future-of-work",
    "excerpt": "The way we work is changing rapidly. AI agents are emerging as a powerful solution to handle tasks that once required entire teams.",
    "content": "The way we work is changing rapidly. AI agents are emerging as a powerful solution to handle tasks that once required entire teams. In this article, we explore why AI agents represent the next evolution of workplace automation and how they're already transforming industries.",
    "image": "/blogs/blog3.png",
    "author": "Mayray AI Team",
    "category": "AI Automation",
    "readTime": "6 min read",
    "tags": [
      "AI Agents",
      "Future of Work",
      "Automation"
    ],
    "status": "published",
    "publishedAt": "2026-09-17T01:55:06.798Z",
    "metaTitle": null,
    "metaDescription": null,
    "createdAt": "2026-09-17T01:55:06.798Z"
  },
  {
    "id": "cmu4vnfhu0018rv3je2ghb3uz",
    "title": "Tasks You Should Automate in Your Business Right Now",
    "slug": "tasks-you-should-automate-in-your-business-right-now",
    "excerpt": "If your team is overwhelmed with repetitive work, you are not alone. The good news? Many of these tasks can be automated instantly with AI agents.",
    "content": "If your team is overwhelmed with repetitive work, you are not alone. The good news? Many of these tasks can be automated instantly with AI agents. From email management to data entry, we break down the top tasks you should automate to save time and boost productivity.",
    "image": "/blogs/blog2.png",
    "author": "Mayray AI Team",
    "category": "AI Automation",
    "readTime": "4 min read",
    "tags": [
      "Automation",
      "Productivity",
      "AI"
    ],
    "status": "published",
    "publishedAt": "2026-09-17T01:55:06.034Z",
    "metaTitle": null,
    "metaDescription": null,
    "createdAt": "2026-09-17T01:55:06.034Z"
  },
  {
    "id": "cmu4vl8k4000scw0wzmcgfjno",
    "title": "How AI Automation is Transforming Modern Businesses in 2026",
    "slug": "how-ai-automation-is-transforming-modern-businesses-2026",
    "excerpt": "Businesses today are under constant pressure to move faster, reduce costs, and deliver better customer experiences. AI automation is no longer a luxury — it's a competitive necessity.",
    "content": "Businesses today are under constant pressure to move faster, reduce costs, and deliver better customer experiences. AI automation is no longer a luxury — it's a competitive necessity. In this article, we explore how leading companies are leveraging intelligent AI agents to transform their operations, from customer support to internal workflows.",
    "image": "/blogs/blog1.png",
    "author": "Mayray AI Team",
    "category": "AI Automation",
    "readTime": "5 min read",
    "tags": [
      "AI",
      "Automation",
      "Business"
    ],
    "status": "published",
    "publishedAt": "2026-09-17T01:53:23.852Z",
    "metaTitle": null,
    "metaDescription": null,
    "createdAt": "2026-09-17T01:53:23.859Z"
  },
  {
    "id": "cmu4vl8k4000tcw0weq0391wj",
    "title": "5 Workflows Every Team Should Automate First",
    "slug": "5-workflows-every-team-should-automate-first",
    "excerpt": "Not sure where to start with automation? These five high-impact workflows deliver the fastest ROI.",
    "content": "<p>When teams begin their automation journey, the hardest part is knowing where to start. Based on hundreds of deployments, these five workflows — inbox triage, lead routing, meeting scheduling, invoice processing, and customer follow-ups — consistently deliver the quickest wins...</p>",
    "image": "/blogs/blog2.png",
    "author": "Mayray AI Team",
    "category": "AI Automation",
    "readTime": "5 min read",
    "tags": [
      "automation",
      "workflows",
      "productivity"
    ],
    "status": "published",
    "publishedAt": "2026-09-10T01:53:23.852Z",
    "metaTitle": null,
    "metaDescription": null,
    "createdAt": "2026-09-17T01:53:23.859Z"
  },
  {
    "id": "cmu4vl8k4000ucw0wwuc7bbl6",
    "title": "AI Agents vs. Traditional Automation: What's the Difference?",
    "slug": "ai-agents-vs-traditional-automation",
    "excerpt": "Rule-based automation breaks when reality changes. Here's how AI agents adapt, reason, and decide like a human employee.",
    "content": "<p>Traditional automation follows rigid if-this-then-that rules and fails the moment something unexpected happens. AI agents, by contrast, understand context, make judgment calls, and learn from feedback — handling the messy edge cases that used to require a person. In this post we break down where each approach fits...</p>",
    "image": "/blogs/blog3.png",
    "author": "Mayray AI Team",
    "category": "AI Automation",
    "readTime": "5 min read",
    "tags": [
      "AI",
      "agents",
      "automation"
    ],
    "status": "published",
    "publishedAt": "2026-09-03T01:53:23.852Z",
    "metaTitle": null,
    "metaDescription": null,
    "createdAt": "2026-09-17T01:53:23.859Z"
  }
];
