// GENERATED by `npm run content:snapshot` in backend/ from the live database. Edit content in the admin, then re-run.
import type { IntegrationFixture, FeatureFixture, UseCaseFixture, TestimonialFixture, ScalingStepFixture, IndustryRoiFixture } from "./types";

export const INTEGRATIONS: IntegrationFixture[] = [
  {
    "id": "cmu4vl6wq0001cw0w7luz8kr5",
    "name": "Gmail",
    "logo": "/svg/gmail.svg",
    "description": "Email automation and management",
    "category": "communication",
    "isActive": true,
    "order": 0
  },
  {
    "id": "cmu4vl6wq0004cw0wcmfbhhup",
    "name": "Google Calendar",
    "logo": "/svg/google-calendar 1.svg",
    "description": "Calendar scheduling and event management",
    "category": "productivity",
    "isActive": true,
    "order": 1
  },
  {
    "id": "cmu4vl6wq0006cw0wmv567cry",
    "name": "Google Drive",
    "logo": "/svg/google-drive.svg",
    "description": "Cloud file storage and sharing",
    "category": "storage",
    "isActive": true,
    "order": 2
  },
  {
    "id": "cmu4vl6wq000gcw0wur0fv9c8",
    "name": "Google Keep",
    "logo": "/svg/google-keep.svg",
    "description": "Note-taking and task management",
    "category": "productivity",
    "isActive": true,
    "order": 3
  },
  {
    "id": "cmu4vl6wq0005cw0whxukhh9r",
    "name": "Microsoft Teams",
    "logo": "/svg/microsoft-team-management-business-office 1.svg",
    "description": "Team communication and collaboration",
    "category": "communication",
    "isActive": true,
    "order": 4
  },
  {
    "id": "cmu4vl6wq0002cw0w5q1eaz9i",
    "name": "Slack",
    "logo": "/globe.svg",
    "description": "Team messaging and workflow automation",
    "category": "communication",
    "isActive": true,
    "order": 5
  },
  {
    "id": "cmu4vl6wq0003cw0w3f5qaryw",
    "name": "Salesforce",
    "logo": "/svg/saleforce.svg",
    "description": "CRM and sales pipeline management",
    "category": "crm",
    "isActive": true,
    "order": 6
  },
  {
    "id": "cmu4vl6wq0009cw0wd07i1q5i",
    "name": "LinkedIn",
    "logo": "/svg/linkedin.svg",
    "description": "Professional networking and lead generation",
    "category": "other",
    "isActive": true,
    "order": 7
  },
  {
    "id": "cmu4vl6wq0007cw0w07ovhla4",
    "name": "Excel",
    "logo": "/svg/excel.svg",
    "description": "Spreadsheet data analysis and reporting",
    "category": "productivity",
    "isActive": true,
    "order": 8
  },
  {
    "id": "cmu4vl6wq000ccw0wvfsj7suu",
    "name": "Word",
    "logo": "/svg/ms-word 1.svg",
    "description": "Document creation and management",
    "category": "productivity",
    "isActive": true,
    "order": 9
  },
  {
    "id": "cmu4vl6wq000fcw0wzasnk9o3",
    "name": "PowerPoint",
    "logo": "/svg/microsoft-powerpoint-2013-logo 1.svg",
    "description": "Presentation creation and management",
    "category": "productivity",
    "isActive": true,
    "order": 10
  },
  {
    "id": "cmu4vl6wq0008cw0wg89430ig",
    "name": "Outlook",
    "logo": "/svg/ms-outlook 2.svg",
    "description": "Email and calendar management",
    "category": "communication",
    "isActive": true,
    "order": 11
  },
  {
    "id": "cmu4vl6wq000ecw0w0f7r1yu2",
    "name": "Chrome",
    "logo": "/svg/chrome.svg",
    "description": "Web browsing and extension automation",
    "category": "other",
    "isActive": true,
    "order": 12
  },
  {
    "id": "cmu4vl6wq000dcw0wb3f30bey",
    "name": "Instagram",
    "logo": "/svg/instagram.svg",
    "description": "Social media management and marketing",
    "category": "other",
    "isActive": true,
    "order": 13
  },
  {
    "id": "cmu4vl6wq000bcw0wlgqk31jx",
    "name": "SAP",
    "logo": "/svg/sap 1.svg",
    "description": "Enterprise resource planning integration",
    "category": "other",
    "isActive": true,
    "order": 14
  },
  {
    "id": "cmu4vmv45000hrv3jo7td2gcm",
    "name": "Zendesk",
    "logo": "/svg/zendesk.svg",
    "description": "Customer support ticket management",
    "category": "communication",
    "isActive": true,
    "order": 15
  },
  {
    "id": "cmu4vmvmj000irv3jy63fmts1",
    "name": "Whatsapp",
    "logo": "/svg/whatsapp.svg",
    "description": "Messaging and customer communication",
    "category": "communication",
    "isActive": true,
    "order": 16
  },
  {
    "id": "cmu4vmw5m000jrv3jmp2j3jhi",
    "name": "Wordpress",
    "logo": "/svg/WordPress.svg",
    "description": "Content management and website automation",
    "category": "other",
    "isActive": true,
    "order": 17
  },
  {
    "id": "cmu4vmwou000krv3jozwb7gpo",
    "name": "Stripe",
    "logo": "/svg/Stripe.svg",
    "description": "Payment processing and billing automation",
    "category": "other",
    "isActive": true,
    "order": 18
  },
  {
    "id": "cmu4vmx6s000lrv3j5bollw16",
    "name": "Ebay",
    "logo": "/svg/EBay.svg",
    "description": "E-commerce marketplace integration",
    "category": "other",
    "isActive": true,
    "order": 19
  },
  {
    "id": "cmu4vmxpg000mrv3j973x6ii2",
    "name": "Amazon",
    "logo": "/svg/Amazon.svg",
    "description": "E-commerce marketplace integration",
    "category": "other",
    "isActive": true,
    "order": 20
  },
  {
    "id": "cmu4vmy7s000nrv3j1bhm3tsl",
    "name": "Woocommerce",
    "logo": "/svg/WooCommerce.svg",
    "description": "E-commerce store management",
    "category": "other",
    "isActive": true,
    "order": 21
  },
  {
    "id": "cmu4vmypt000orv3jst1z3bxu",
    "name": "Sheet",
    "logo": "/globe.svg",
    "description": "Spreadsheet automation",
    "category": "productivity",
    "isActive": true,
    "order": 22
  },
  {
    "id": "cmu4vl6wq000acw0wkimajlat",
    "name": "Sheets",
    "logo": "/globe.svg",
    "description": "Google Sheets automation",
    "category": "productivity",
    "isActive": true,
    "order": 23
  }
];

export const FEATURES: FeatureFixture[] = [
  {
    "id": "cmu4vml6k00057ioyf4hlvlno",
    "title": "AI-Powered HR Automation",
    "description": "Automate hiring workflows, onboarding, and employee management processes with intelligent AI agents.",
    "videoUrl": "/features-svg/6.mp4",
    "thumbnail": "/blogbg.png",
    "apps": [
      "Gmail",
      "LinkedIn",
      "Sheet"
    ],
    "group": "B",
    "isActive": true,
    "order": 0
  },
  {
    "id": "cmu4vmjtf0000rv3jbb960edl",
    "title": "AI-Powered HR Automation",
    "description": "Automate hiring workflows, onboarding, and employee management processes with intelligent AI agents.",
    "videoUrl": "/features-svg/6.mp4",
    "thumbnail": null,
    "apps": [
      "Gmail",
      "LinkedIn",
      "Sheet"
    ],
    "group": "A2",
    "isActive": true,
    "order": 0
  },
  {
    "id": "cmu4vmj6o00037ioyp56lc2oj",
    "title": "AI Office Automation",
    "description": "Automate repetitive tasks across your business from data entry to internal workflows so your team can focus on high-impact work.",
    "videoUrl": "/features-svg/6.mp4",
    "thumbnail": null,
    "apps": [
      "Word",
      "Keep",
      "X",
      "Chrome",
      "LinkedIn",
      "Instagram"
    ],
    "group": "A2",
    "isActive": true,
    "order": 0
  },
  {
    "id": "cmu4vmft800007ioyzz0dfur6",
    "title": "AI Office Automation",
    "description": "Automate repetitive tasks across your business from data entry to internal workflows so your team can focus on high-impact work.",
    "videoUrl": "/features-svg/6.mp4",
    "thumbnail": null,
    "apps": [
      "Excel",
      "Word",
      "Google Keep"
    ],
    "group": "A",
    "isActive": true,
    "order": 0
  },
  {
    "id": "cmu4vmm7l00067ioyey4nwdb5",
    "title": "AI Automation for E-commerce",
    "description": "From order handling to customer queries automate your entire sales and fulfillment workflow.",
    "videoUrl": "/features-svg/7.mp4",
    "thumbnail": "/bgg.png",
    "apps": [
      "Wordpress",
      "Stripe",
      "Ebay",
      "Amazon",
      "Woocommerce"
    ],
    "group": "B",
    "isActive": true,
    "order": 1
  },
  {
    "id": "cmu4vmksx0001rv3jreiq0axg",
    "title": "AI Automation for E-commerce",
    "description": "From order handling to customer queries automate your entire sales and fulfillment workflow.",
    "videoUrl": "/features-svg/7.mp4",
    "thumbnail": null,
    "apps": [
      "Wordpress",
      "Stripe",
      "Ebay",
      "Amazon",
      "Woocommerce"
    ],
    "group": "A2",
    "isActive": true,
    "order": 1
  },
  {
    "id": "cmu4vmk5e00047ioykz77c3qi",
    "title": "Email & Communication Management",
    "description": "AI handles inbox sorting, replies, follow-ups, and internal communication reducing overload and response time.",
    "videoUrl": "/features-svg/7.mp4",
    "thumbnail": null,
    "apps": [
      "Gmail",
      "Slack",
      "Teams"
    ],
    "group": "A2",
    "isActive": true,
    "order": 1
  },
  {
    "id": "cmu4vmh3400017ioyev8sr94i",
    "title": "Email & Communication Management",
    "description": "AI handles inbox sorting, replies, follow-ups, and internal communication reducing overload and response time.",
    "videoUrl": "/features-svg/7.mp4",
    "thumbnail": null,
    "apps": [
      "Gmail",
      "Slack",
      "Microsoft Teams"
    ],
    "group": "A",
    "isActive": true,
    "order": 1
  },
  {
    "id": "cmu4vmi6m00027ioyhshkb6re",
    "title": "AI-Powered Customer Support",
    "description": "Provide instant, intelligent responses to customers 24/7 without increasing support costs.",
    "videoUrl": "/features-svg/8.mp4",
    "thumbnail": null,
    "apps": [
      "Salesforce",
      "Whatsapp",
      "Zendesk"
    ],
    "group": "A",
    "isActive": true,
    "order": 2
  }
];

export const USE_CASES: UseCaseFixture[] = [
  {
    "id": "cmu4vl828000kcw0wpgsorirh",
    "title": "Marketing",
    "description": "Drive faster growth with automated campaigns and lead generation.",
    "icon": "/agentareacard/noun-marketing-8045132 1.svg",
    "category": "marketing",
    "isActive": true,
    "order": 0
  },
  {
    "id": "cmu4vl828000lcw0wv7qn109f",
    "title": "Sales",
    "description": "Level up your sales cycle to close more deals with AI-driven outreach.",
    "icon": "/agentareacard/noun-sales-8011863 1.svg",
    "category": "sales",
    "isActive": true,
    "order": 1
  },
  {
    "id": "cmu4vl828000mcw0wa944nfwy",
    "title": "Operations",
    "description": "Get teams and tools working together seamlessly with smart workflows.",
    "icon": "/agentareacard/noun-it-operations-1909143 1.svg",
    "category": "operations",
    "isActive": true,
    "order": 2
  },
  {
    "id": "cmu4vl828000ncw0wjf6c39gm",
    "title": "Customer Experience",
    "description": "Manage time as well as you manage customer relationships with AI support.",
    "icon": "/agentareacard/noun-customer-experience-7440062 1.svg",
    "category": "customer_experience",
    "isActive": true,
    "order": 3
  },
  {
    "id": "cmu4vl828000ocw0w7aotxxfc",
    "title": "Finance",
    "description": "Automate invoicing, expense tracking, and financial reporting.",
    "icon": "/agentareacard/noun-finance-7033868 1.svg",
    "category": "finance",
    "isActive": true,
    "order": 4
  },
  {
    "id": "cmu4vn5bq000qrv3jnnnolozb",
    "title": "Information Technology",
    "description": "Efficiently scale and control your IT infrastructure with AI agents.",
    "icon": "/agentareacard/noun-information-technology-3918785 1.svg",
    "category": "it",
    "isActive": true,
    "order": 5
  },
  {
    "id": "cmu4vl828000pcw0w63zl5upf",
    "title": "IT",
    "description": "Infrastructure automation and control",
    "icon": null,
    "category": "it",
    "isActive": true,
    "order": 5
  },
  {
    "id": "cmu4vn6aq000rrv3jbc5aeo6j",
    "title": "People",
    "description": "Get your HR processes running smoothly from hiring to onboarding.",
    "icon": "/agentareacard/noun-it-operations-1909143 1 (1).svg",
    "category": "hr",
    "isActive": true,
    "order": 6
  },
  {
    "id": "cmu4vl828000qcw0wk2h2c1b2",
    "title": "People / HR",
    "description": "Hiring to onboarding automation",
    "icon": null,
    "category": "hr",
    "isActive": true,
    "order": 6
  },
  {
    "id": "cmu4vl828000rcw0wu96g8j0g",
    "title": "Workplace Productivity",
    "description": "Automate busy work to focus on what truly matters for your business.",
    "icon": "/agentareacard/noun-customer-experience-7440062 1 (1).svg",
    "category": "productivity",
    "isActive": true,
    "order": 7
  }
];

export const TESTIMONIALS: TestimonialFixture[] = [
  {
    "id": "cmu4vl7l1000hcw0wwqv77fbx",
    "quote": "Mayray AI replaced hours of manual work overnight. Before using Mayray AI, our team was buried in repetitive tasks. Now, workflows run automatically, and we have saved over 20+ hours every week.",
    "name": "Olivia Chen",
    "role": "Operations Manager",
    "company": "SaaS Company",
    "avatar": "/svg/avatar.svg",
    "rating": 5,
    "isActive": true,
    "order": 0
  },
  {
    "id": "cmu4vl7l1000icw0wzan8dlgf",
    "quote": "It feels like we hired a full support team without the cost. Mayray AI handles customer queries instantly, 24/7. Our response time dropped dramatically, and customer satisfaction has never been higher.",
    "name": "Ethan Brooks",
    "role": "Head of Support",
    "company": "E-commerce Brand",
    "avatar": "/svg/avatar.svg",
    "rating": 5,
    "isActive": true,
    "order": 1
  },
  {
    "id": "cmu4vl7l1000jcw0w10bcdvld",
    "quote": "We scaled faster without increasing our team size. Mayray AI did not just automate tasks it gave us the ability to grow without operational bottlenecks. The ROI was clear within the first month.",
    "name": "Daniel Foster",
    "role": "Founder",
    "company": "Digital Agency",
    "avatar": "/svg/avatar.svg",
    "rating": 5,
    "isActive": true,
    "order": 2
  }
];

export const SCALING_STEPS: ScalingStepFixture[] = [
  {
    "id": "cmu4vnddy000wrv3j0357d4o3",
    "step": "01",
    "title": "Free Process Health Check",
    "body": "Our consultants analyze your workflows to find where AI and automation can improve productivity and lower costs.",
    "icon": null,
    "isCard": false,
    "order": 0
  },
  {
    "id": "cmu4vnddy000xrv3jkp9a9dr0",
    "step": "02",
    "title": "Personalized AI & Automation Roadmap",
    "body": "We create a tailored roadmap with AI solutions and projected time and cost savings.",
    "icon": null,
    "isCard": false,
    "order": 1
  },
  {
    "id": "cmu4vnddz000yrv3jzhtqj5wl",
    "step": "03",
    "title": "Implementation & Testing",
    "body": "Our engineers automate your tasks and integrate your systems, ensuring everything works seamlessly.",
    "icon": null,
    "isCard": false,
    "order": 2
  },
  {
    "id": "cmu4vnddz000zrv3j0rqaaxm1",
    "step": "04",
    "title": "Ongoing Support & Optimization",
    "body": "Stay optimized with our support packages — updates, maintenance, and continuous improvements included.",
    "icon": null,
    "isCard": false,
    "order": 3
  },
  {
    "id": "cmu4vnddz0010rv3jz1brjecs",
    "step": "—",
    "title": "Expertise That Turns Strategy Into Measurable Results",
    "body": "Backed by experts in business, sales, marketing, and technology, our AI solutions are research-driven and tested to deliver reliable automation you can trust.",
    "icon": null,
    "isCard": true,
    "order": 0
  },
  {
    "id": "cmu4vnddz0011rv3jqqyht5au",
    "step": "—",
    "title": "Customer Training",
    "body": "We train your team to confidently use AI and automation in daily workflows. Through guided sessions and real-world examples, we ensure smooth adoption, faster onboarding, and long-term success.",
    "icon": null,
    "isCard": true,
    "order": 1
  }
];

export const INDUSTRY_ROI: IndustryRoiFixture[] = [
  {
    "id": "cmu4vme9c0000dsumshl7lrev",
    "industry": "Car",
    "cvr": "400%",
    "showUp": "20-40%",
    "image": "/assets/car.png",
    "useCases": [
      "Lead Qualification",
      "Support",
      "Appointment Confirmation"
    ],
    "isActive": true,
    "order": 0
  },
  {
    "id": "cmu4vmfcw0001dsumy0qc9ig8",
    "industry": "Real estate",
    "cvr": "250%",
    "showUp": "15-30%",
    "image": "/assets/car.png",
    "useCases": [
      "Property Inquiry",
      "Tour Scheduling",
      "Agent Follow-up"
    ],
    "isActive": true,
    "order": 1
  },
  {
    "id": "cmu4vmgki0002dsume15w2o64",
    "industry": "Legal",
    "cvr": "180%",
    "showUp": "40-60%",
    "image": "/assets/car.png",
    "useCases": [
      "Case Intake",
      "Conflict Checks",
      "Client Onboarding"
    ],
    "isActive": true,
    "order": 2
  },
  {
    "id": "cmu4vmhoq0003dsum72eugnem",
    "industry": "Insurance",
    "cvr": "320%",
    "showUp": "25-45%",
    "image": "/assets/car.png",
    "useCases": [
      "Claims Processing",
      "Quote Generation",
      "Renewal Reminders"
    ],
    "isActive": true,
    "order": 3
  }
];
