// GENERATED by `npm run content:snapshot` in backend/ from the live database. Pages still edited in the old page editor.
import type { PageContentFixture } from "./types";

export const PAGE_CONTENT: PageContentFixture[] = [
  {
    "page": "blog",
    "section": "featured",
    "key": "label",
    "value": "Featured Article Spotlight",
    "order": 0
  },
  {
    "page": "blog",
    "section": "grid",
    "key": "empty_description",
    "value": "Try adjusting your search query or switching selected categories.",
    "order": 0
  },
  {
    "page": "blog",
    "section": "grid",
    "key": "empty_title",
    "value": "No articles found",
    "order": 0
  },
  {
    "page": "blog",
    "section": "grid",
    "key": "heading",
    "value": "All Articles",
    "order": 0
  },
  {
    "page": "blog",
    "section": "grid",
    "key": "subheading",
    "value": "Showing top resources & tutorials",
    "order": 0
  },
  {
    "page": "blog",
    "section": "hero",
    "key": "badge",
    "value": "Mayray AI Knowledge Hub & Insights",
    "order": 0
  },
  {
    "page": "blog",
    "section": "hero",
    "key": "clear_button",
    "value": "Clear",
    "order": 0
  },
  {
    "page": "blog",
    "section": "hero",
    "key": "headline",
    "value": "Insights & Guides on AI Automation",
    "order": 0
  },
  {
    "page": "blog",
    "section": "hero",
    "key": "search_placeholder",
    "value": "Search articles by keyword, topic, or industry...",
    "order": 0
  },
  {
    "page": "blog",
    "section": "hero",
    "key": "subtitle",
    "value": "Discover actionable strategies, technical breakdowns, and industry case studies on scaling business operations with autonomous AI agents.",
    "order": 0
  },
  {
    "page": "blog",
    "section": "newsletter",
    "key": "badge",
    "value": "Mayray AI Weekly Dispatch",
    "order": 0
  },
  {
    "page": "blog",
    "section": "newsletter",
    "key": "button_label",
    "value": "Subscribe Free",
    "order": 0
  },
  {
    "page": "blog",
    "section": "newsletter",
    "key": "headline",
    "value": "Stay ahead with practical AI automation breakdowns",
    "order": 0
  },
  {
    "page": "blog",
    "section": "newsletter",
    "key": "placeholder",
    "value": "Enter your work email...",
    "order": 0
  },
  {
    "page": "blog",
    "section": "newsletter",
    "key": "subtitle",
    "value": "Join 15,000+ operations leaders, founders, and engineers. Get our weekly newsletter covering autonomous agents, CRM integrations, and ROI benchmarks.",
    "order": 0
  },
  {
    "page": "blog",
    "section": "newsletter",
    "key": "success_detail",
    "value": "Check your inbox for our latest edition and welcome guide.",
    "order": 0
  },
  {
    "page": "blog",
    "section": "newsletter",
    "key": "success_message",
    "value": "You're subscribed!",
    "order": 0
  },
  {
    "page": "blog",
    "section": "newsletter",
    "key": "trust_text",
    "value": "No spam guarantee",
    "order": 0
  },
  {
    "page": "blog",
    "section": "seo",
    "key": "description",
    "value": "Discover actionable strategies, technical breakdowns, and industry case studies on scaling business operations with autonomous AI agents.",
    "order": 0
  },
  {
    "page": "blog",
    "section": "seo",
    "key": "keywords",
    "value": "AI blog, automation guides, business AI insights",
    "order": 0
  },
  {
    "page": "blog",
    "section": "seo",
    "key": "title",
    "value": "Blog | AI Automation Insights & Guides | Mayray AI",
    "order": 0
  },
  {
    "page": "blog_detail",
    "section": "author",
    "key": "bio",
    "value": "Specializes in designing autonomous AI agents, sub-300ms voice pipelines, and enterprise CRM workflow integrations for high-growth operations.",
    "order": 0
  },
  {
    "page": "blog_detail",
    "section": "hero",
    "key": "back_label",
    "value": "Back to All Articles",
    "order": 0
  },
  {
    "page": "blog_detail",
    "section": "hero",
    "key": "copied_label",
    "value": "Copied!",
    "order": 0
  },
  {
    "page": "blog_detail",
    "section": "hero",
    "key": "copy_link_label",
    "value": "Copy Link",
    "order": 0
  },
  {
    "page": "blog_detail",
    "section": "hero",
    "key": "share_label",
    "value": "Share:",
    "order": 0
  },
  {
    "page": "blog_detail",
    "section": "related",
    "key": "heading",
    "value": "Related Articles",
    "order": 0
  },
  {
    "page": "blog_detail",
    "section": "related",
    "key": "read_label",
    "value": "Read Article",
    "order": 0
  },
  {
    "page": "blog_detail",
    "section": "related",
    "key": "view_all_label",
    "value": "View All Articles",
    "order": 0
  },
  {
    "page": "blog_detail",
    "section": "seo",
    "key": "description",
    "value": "Read this article from Mayray AI.",
    "order": 0
  },
  {
    "page": "blog_detail",
    "section": "seo",
    "key": "title",
    "value": "Blog Post | Mayray AI",
    "order": 0
  },
  {
    "page": "not_found",
    "section": "not_found",
    "key": "badge",
    "value": "404",
    "order": 0
  },
  {
    "page": "not_found",
    "section": "not_found",
    "key": "button_label",
    "value": "Back to home",
    "order": 0
  },
  {
    "page": "not_found",
    "section": "not_found",
    "key": "description",
    "value": "The page you're looking for doesn't exist or has been moved.",
    "order": 0
  },
  {
    "page": "not_found",
    "section": "not_found",
    "key": "title",
    "value": "Page not found",
    "order": 0
  },
  {
    "page": "not_found",
    "section": "seo",
    "key": "description",
    "value": "The page you are looking for does not exist or has been moved.",
    "order": 0
  },
  {
    "page": "not_found",
    "section": "seo",
    "key": "title",
    "value": "Page Not Found | Mayray AI",
    "order": 0
  }
];
